-- Create the contacts table
create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  name text not null,
  email text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.contacts enable row level security;

-- Create a policy to allow anyone (anon) to insert data
create policy "Enable insert for anyone"
on public.contacts
for insert
to anon
with check (true);

-- Optional: Create a policy to allow service_role (admins) to view data
-- (This is default behavior for service_role, but good to be explicit if needed for other roles)
-- create policy "Enable read for service_role only"
-- on public.contacts
-- for select
-- to service_role
-- using (true);
