-- Create the posts table
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  slug text not null unique,
  title text not null,
  excerpt text,
  content text not null,
  published boolean default false,
  image_url text
);

-- Enable Row Level Security (RLS)
alter table public.posts enable row level security;

-- Create a policy to allow anyone to read published posts
create policy "Enable read access for all users"
on public.posts
for select
using (published = true);

-- Create a policy to allow service_role (admins) to do everything
-- (Implicitly allowed, but good for documentation)
